### ISSUE TITLE
Tokio thread panics when `Client` is not connected to cluster

### ISSUE THREAD

**Issue by jdhoek** [luncj/etcd-rs#12]
I am trying to catch the case where the `Client` class can't successfully connect to the Etcd cluster and exit with a user friendly error message. However, my current approach leads to a panic in one of Tokio's threads, which is output to stderr.

Minimal reproduction case:

```toml
[dependencies]
etcd-rs = "0.2.0-alpha.5"
tokio = "0.2.0-alpha.6"
```

```rust
use std::process;

use etcd_rs::{Client, ClientConfig, KeyRange, RangeRequest};

async fn get(client: &Client, name: &str) -> Result<(), String> {
    let req = RangeRequest::new(KeyRange::key(name));

    let mut resp = match client.kv().range(req).await {
        Ok(resp) => resp,
        Err(_) => return Err("Failed to connect to Etcd cluster.".to_owned())
    };
    let kvs = resp.take_kvs();

    match kvs.get(0) {
        Some(v) => {
            match std::str::from_utf8(v.value()) {
                Ok(v) => {
                    println!("{}", v);
                    return Ok(())
                },
                Err(e) => panic!("Invalid UTF-8 sequence: {}", e),
            };
        },
        None => {
            eprintln!("No key with name '{}' found.", name);
            process::exit(4);
        }
    }
}

async fn connect(endpoints: Vec<String>) -> Client {
    let client = Client::connect(ClientConfig {
        endpoints,
        auth: None,
    }).await;

    match client {
        Ok(c) => c,
        Err(_) => {
            eprintln!("Failed to create Etcd client.");
            process::exit(2);
        }
    }
}

#[tokio::main]
async fn main() {
    let client: Client = connect(vec!["https://localhost:2379".to_owned()]).await;

    match get(&client, "foo").await {
        Err(e) => {
            eprintln!("{}", e);
            process::exit(2);
        },
        _ => (),
    }
}
```

When the endpoint is available, this code works (provided a key named `foo` exists).

When the endpoint is not available, the `connect` method succeeds, but `client.kv().range(req).await` fails with an `Err`, and I attempt to gracefully exit, but in the terminal I see this:

```
thread 'Failed to connect to Etcd cluster.tokio-runtime-worker-4
' panicked at 'called `Result::unwrap()` on an `Err` value: Status { code: Unknown, message: "Client: buffered service failed: load balancer discovery error: error trying to connect: Connection refused (os error 111)" }', src/libcore/result.rs:1165:5
```

My own message and the message from the Tokio thread get jumbled together.

Is this panic something that can be caught and handled in `etcd-rs`, or is my approach wrong?

**Comment by ccc13** [comment]
There are two bi-directional RPC calling when the client constructed, and it roughly `unwrap` (and panic). They are:
- https://github.com/ccc13/etcd-rs/blob/master/src/watch/mod.rs#L82: for receiving `watch` event
- https://github.com/ccc13/etcd-rs/blob/master/src/lease/mod.rs#L102: for receiving `lease` event

I will try to handle the errors gracefully in the next few days. Thanks for reporting. 
(And I think I need to add more automatic integration testing)
