### ISSUE TITLE
Client::connect spawns tasks for watch

### ISSUE THREAD

**Issue by znewman01** [luncj/etcd-rs#25]
Hi, thanks for the library! I'm using it in a project, and it's been working well.

I've noticed, however, that `Client::connect` spawns a task for the "watch" stream ("lease" too).

This has a couple of drawbacks:
- General overhead: why spawn if you're not going to use it? Also, it means that I need to use `#[tokio::test(threaded_scheduler)]` in my integration tests.
- Extra logging noise: when I shut down a runtime, (e.g. in a CLI client and integration tests), there's a panic along the lines of:

    ```
    thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Status { code: Unknown, message: "transport error: connection error: broken pipe" }', /home/zjn/.cargo/registry/src/github.com-1ecc6299db9ec823/etcd-rs-0.2.1/src/watch/mod.rs:78:31
    ```

What would you think about the following?

1. having an option in `ClientConfig` to disable these
1. lazily spawning these tasks when a client uses "watch"
1. a method to trigger clean shutdown of the task (e.g. using a [`tokio::sync::oneshot`](https://docs.rs/tokio/0.2.13/tokio/sync/oneshot/index.html) to signal to the watch task that it should wrap up)

In particular, I think (2+3) go well together---you could have a `RwLock<Option<Client>>`. In most calls, you'd just use the `Some(Client)` that was there (a cheap read lock), but you might sometimes need to grab the write lock the first time you use one of these clients. The shutdown bit would grab the write lock too.

Let me know what you thing (I may be able to follow up with a PR).

**Comment by luncj** [comment]
I am glad you found something useful here.

> In particular, I think (2+3) go well together

I agreed. It's a better way.

> (I may be able to follow up with a PR).

That would be great and thank you in advance.
