### ISSUE TITLE
How to send PutRequest with ttl

### ISSUE THREAD

**Issue by Vegetarianz** [luncj/etcd-rs#31]
I see:

let mut req = PutRequest::new(key, value);
req.set_lease(leaseID);

but there seems no way to get the leaseID

**Comment by luncj** [comment]
> but there seems no way to get the leaseID

https://github.com/luncj/etcd-rs/blob/4e7b5185bb2c0f9e855e490aa5a18adc4dcb66f9/examples/lease.rs#L23-L36

**Comment by Vegetarianz** [comment]
tks
