### ISSUE TITLE
Upgrade to tokio 0.3

### ISSUE THREAD

**Issue by hodgesds** [luncj/etcd-rs#40]
Any plans to support tokio 0.3? I can start a branch with some changes I'm testing.

**Comment by luncj** [comment]
That would be great. 😄

**Comment by ramonberrutti** [comment]
I think that tonic needs to upgrade to tokio 0.3 first.

https://github.com/hyperium/tonic/pull/488

**Comment by zserik** [comment]
tonic progress: https://github.com/hyperium/tonic/commit/fdda5ae26ace4706cb8faf56ccd35513b5de26c5

**Comment by zserik** [comment]
[Tonic v0.4](https://github.com/hyperium/tonic/releases/tag/v0.4.0) was released yesterday.

**Comment by zserik** [comment]
I think this issue can be closed.

**Comment by luncj** [comment]
closed via #44
